# Generated by Django 3.0.5 on 2020-09-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_auto_20200901_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='contact',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='info',
            name='pyear',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='info',
            name='tenure1',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='info',
            name='tenure2',
            field=models.IntegerField(default='Till-Now'),
        ),
        migrations.AlterField(
            model_name='info',
            name='uidai',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='info',
            name='ward_no',
            field=models.IntegerField(),
        ),
    ]
