# Generated by Django 3.0.5 on 2020-09-25 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_auto_20200913_0339'),
    ]

    operations = [
        migrations.DeleteModel(
            name='info',
        ),
    ]
