# Generated by Django 3.0.5 on 2020-09-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='s_field',
        ),
        migrations.AddField(
            model_name='info',
            name='id_number',
            field=models.IntegerField(default=9628513166),
        ),
        migrations.AddField(
            model_name='info',
            name='profile_img',
            field=models.ImageField(default='NONE', upload_to='property/%m/%d/'),
        ),
    ]
