# Generated by Django 3.0.5 on 2020-09-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_auto_20200926_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='id_number',
            field=models.IntegerField(default=4027296979, unique=True),
        ),
    ]
