# Generated by Django 3.0.5 on 2020-09-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_auto_20200926_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='id_number',
            field=models.IntegerField(default=6086391723, unique=True),
        ),
    ]
