# Generated by Django 3.0.5 on 2020-09-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0008_auto_20200926_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='id_number',
            field=models.IntegerField(default=7275102352, unique=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='profile_img',
            field=models.ImageField(upload_to='media/%m/%d/'),
        ),
    ]
