# Generated by Django 3.0.5 on 2020-09-26 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0009_auto_20200926_0305'),
    ]

    operations = [
        migrations.DeleteModel(
            name='info',
        ),
    ]
