# Generated by Django 3.0.5 on 2020-09-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0011_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='photo_main',
        ),
        migrations.AlterField(
            model_name='info',
            name='id_number',
            field=models.IntegerField(default=2217746310, unique=True),
        ),
    ]
