# Generated by Django 3.0.5 on 2020-09-26 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0012_auto_20200926_1606'),
    ]

    operations = [
        migrations.DeleteModel(
            name='info',
        ),
    ]
