# Generated by Django 3.0.5 on 2020-09-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '0013_delete_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('photo_main', models.ImageField(upload_to='sena_members/%m/%d/')),
                ('ward_no', models.IntegerField()),
                ('location', models.TextField()),
                ('assembly', models.CharField(max_length=50)),
                ('contact', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('post', models.CharField(max_length=100)),
                ('tenure1', models.PositiveIntegerField()),
                ('tenure2', models.IntegerField(default='Till-Now')),
                ('position', models.CharField(max_length=250)),
                ('blood_g', models.CharField(max_length=20)),
                ('education', models.CharField(max_length=200)),
                ('pyear', models.IntegerField()),
                ('occupation', models.CharField(max_length=220)),
                ('uidai', models.IntegerField()),
                ('id_number', models.IntegerField(default=2553621920, unique=True)),
            ],
        ),
    ]
