# Generated by Django 3.0.5 on 2020-09-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0014_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='id_number',
            field=models.IntegerField(default=8132594991, unique=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='photo_main',
            field=models.ImageField(upload_to='sena_members'),
        ),
    ]
