# Generated by Django 3.0.2 on 2020-09-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0015_auto_20200926_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='id_number',
            field=models.IntegerField(default=8678878391, unique=True),
        ),
    ]
